# Numpy

Matlab è ispirato da MATLAB, e pertanto portato su un linguaggio di programmazione di alto-livello

è in grado di elaborare dati del tipo vettori, matrici, tensori

## Array, proprietà di base :

In [3]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]], dtype = np.float32)

In [4]:
print(a.ndim)

2


In [5]:
print(a.shape)

(2, 3)


In [6]:
print(a.dtype)

float32


In [7]:
print(a)

[[1. 2. 3.]
 [4. 5. 6.]]


## Array, creazione

In [13]:
A = np.ones((2,3))
print(A)

[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
B = np.zeros((4,3))
print(B)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
np.arange(1334,1338)

array([1334, 1335, 1336, 1337])

Si osserva che arrange() è simile a range(), infatti durante la creazione di una libreria tendenzialmente si rimane su stile già definito del linguaggio

In [15]:
np.concatenate([A,B])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Volendo concatenare in orizzontale: axis=1

In [17]:
np.zeros_like #?

<function RandomState.random>

In [20]:
np.random.random((10,3)) # genera numeri casuali tra 0 e 1

array([[0.72509903, 0.38030149, 0.7693153 ],
       [0.26994131, 0.46034388, 0.20580959],
       [0.18156345, 0.60460824, 0.72655316],
       [0.5529971 , 0.06373126, 0.59663109],
       [0.5336355 , 0.05221487, 0.03061499],
       [0.33382303, 0.49656874, 0.47636124],
       [0.45322447, 0.59714313, 0.5340415 ],
       [0.41486552, 0.12939843, 0.39125935],
       [0.46962741, 0.37033243, 0.19117713],
       [0.14505658, 0.75932368, 0.98560563]])

## Linear Algebra

In [21]:
a = np.array([[1,2],[3,4]])
D = np.linalg.det(a)
print(D)

-2.0000000000000004


Provare ad immaginare (esercitare) di calcolare senza utilizzare libreria :)

Il lavoro di sicuro è semplice, ma minimo richiede mezz'ora di tempo, mentre con Numpy è una riga di codice!

## Return Values

Le funzioni Numpy restituiscono o **viste** o **copie**

## Operatori Matematici

In [26]:
a

array([[1, 2],
       [3, 4]])

In [28]:
a > 2

array([[False, False],
       [ True,  True]])

dtype = bool  :)

## Indexing: slices

In [29]:
I[I<10] = 0 # mette uguali a zero le caselle < 10

NameError: name 'I' is not defined

In [30]:
I[[1,3], :] # select 2nd

NameError: name 'I' is not defined

# SciPy

Libreria di *calcolo scientifico* che utilizza NumPy, fornisce più funzioni di utilità per l'ottimizzazione

In [31]:
import numpy as np
from scipy.sparse.csgraph import connected_components
from scipy.sparse import csr_matrix

arr = np.array([
    [0,1,2],
    [1,0,0],
    [2,0,0]
])

In [32]:
newarr = csr_matrix(arr)
print(cconnected_components.newarr)

[[0 1 2]
 [1 0 0]
 [2 0 0]]
